Make it possible to use without exceptions by defining CMRC_NO_EXCEPTIONS
vector-of-bool/cmrc pull request #29
Opened 2021-07-04 22:48 UTC by jorgen

2021-07-05 09:50 UTC, Pospelove commented
Nice feature

2021-07-06 20:09 UTC, vector-of-bool commented on CMakeRC.cmake
> +#if !(defined(__EXCEPTIONS) || defined(__cpp_exceptions) || defined(_CPPUNWIND))
```suggestion
#if !(defined(__EXCEPTIONS) || defined(__cpp_exceptions) || defined(_CPPUNWIND) || defined(CMRC_NO_EXCEPTIONS))
```

2021-07-06 20:11 UTC, vector-of-bool requested changes
Effective and simple. Only one minor tweak requested.

2021-07-06 21:04 UTC, jorgen commented on CMakeRC.cmake
> +#if !(defined(__EXCEPTIONS) || defined(__cpp_exceptions) || defined(_CPPUNWIND))
absolutely

2021-07-07 15:33 UTC, vector-of-bool approved these changes

2021-07-07 15:33 UTC, merged