Add 'TYPE' argument to choose between 'STATIC' and 'OBJECT' libraries
vector-of-bool/cmrc pull request #30
Opened 2021-07-05 08:17 UTC by drdanz

Fixes #28

2021-07-06 20:12 UTC, vector-of-bool commented on CMakeRC.cmake
> +    message("ARG_TYPE = ${ARG_TYPE}")
Have a debug line left over.

2021-07-06 20:13 UTC, vector-of-bool requested changes
Thanks! One minor change requested. Otherwise, LGTM.

2021-07-07 08:16 UTC, drdanz commented on CMakeRC.cmake
> +    message("ARG_TYPE = ${ARG_TYPE}")
Fixed.

2021-07-07 08:17 UTC, drdanz commented
Should be fixed now...

2021-07-07 15:32 UTC, vector-of-bool approved these changes

2021-07-07 15:33 UTC, merged